#! /usr/bin/env python

import sys
import os
import optparse
import datetime
from subprocess import call

progname = os.path.basename(sys.argv[0])

optparser = optparse.OptionParser()
optparser.add_option('-v', '--verbose', dest='verbose', action='store_true',
                     default=False,
                     help='echo commands before executing')
optparser.add_option('--builds', dest='builds',
                     default='ALPHA_SE,ALPHA_FS,MIPS_SE,' + \
                     'SPARC_SE,SPARC_FS',                     help='comma-separated list of build targets to test  '
                     " (default: '%default')" )
optparser.add_option('--variants', dest='variants',
                     default='fast',
                     help='comma-separated list of build variants to test '
                     " (default: '%default')" )
optparser.add_option('--scons-opts', dest='scons_opts', default='',
                     help='scons options', metavar='OPTS')
optparser.add_option('-j', '--jobs', type='int', default=1,
                     help='number of parallel jobs to use')
optparser.add_option('-k', '--keep-going', action='store_true',
                     help='keep going after errors')

(options, tests) = optparser.parse_args()


# split list options on ',' to get Python lists
builds = options.builds.split(',')
variants = options.variants.split(',')

# Call os.system() and raise exception if return status is non-zero
def system(cmd):
    try:
        retcode = call(cmd, shell=True)
        if retcode < 0:
            print >>sys.stderr, "Child was terminated by signal", -retcode
            print >>sys.stderr, "When attemping to execute: %s" % cmd
            sys.exit(1)
        elif retcode > 0:
            print >>sys.stderr, "Child returned", retcode
            print >>sys.stderr, "When attemping to execute: %s" % cmd
            sys.exit(1)
    except OSError, e:
        print >>sys.stderr, "Execution failed:", e
        print >>sys.stderr, "When attemping to execute: %s" % cmd
        sys.exit(1)

# Quote string s so it can be passed as a shell arg
def shellquote(s):
    if ' ' in s:
        s = "'%s'" % s
    return s

if not tests:
    print "No tests specified, just building binaries."
    targets = ['build/%s/m5.%s' % (build, variant)
               for build in builds
               for variant in variants]
elif 'all' in tests:
    targets = ['build/%s/tests/%s' % (build, variant)
               for build in builds
               for variant in variants]
else:
    # Ugly! Since we don't have any quick SPARC_FS tests remove the SPARC_FS target
    # If we ever get a quick SPARC_FS test, this code should be removed
    if 'quick' in tests and 'SPARC_FS' in builds:
        builds.remove('SPARC_FS')
    targets = ['build/%s/tests/%s/%s' % (build, variant, test)
               for build in builds
               for variant in variants
               for test in tests]

scons_opts = options.scons_opts
if options.jobs != 1:
    scons_opts += ' -j %d' % options.jobs
if options.keep_going:
    scons_opts += ' -k'

system('scons IGNORE_STYLE=True %s %s' % (scons_opts, ' '.join(targets)))

sys.exit(0)
